apiVersion: batch/v1
kind: CronJob
metadata:
  name: go-cronjob
  labels:
    label-key: label-value
  annotations:
    annotation-key1: annotation-value1
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      # selector:  ERROR (?) atau karena gaada replica, gatau juga
      #   matchLabels:
      #     label-key1: label-value1
      template:
        metadata:
          name: go-cronjob
          labels:
            name-bebas: go-cronjob
        spec:
          restartPolicy: Never
          containers:
            - name: go-cronjob
              image: vincen320/go-job
          # ports:
          #   -containerPort: 80
